---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "uniqName" . }}"
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
