apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.app}}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{.Values.component}}
  ports:
    - name: http
      port: {{.Values.port}}
      protocol: TCP