description: Curator chart for managing elasticsearch indices
engine: gotpl
home: https://github.com/samsung-cnct/chart-curator
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
keywords:
- logging
- curator
- elasticsearch
- kraken
- delete_indices
maintainers:
- email: samsung.cloudnative@gmail.com
  name: Samsung CNCT
name: curator
sources:
- https://github.com/samsung-cnct/chart-curator
version: 0.0.6
