{{- if .Values.master_create_storage_class }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.master_storage_class_value }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
{{- end }}
