---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name}}
  labels:
    app: {{ template "name" . }}
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
