---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ template "eventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        component: eventrouter
        tier: control-plane-addons
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      serviceAccount: {{ .Values.name }}-{{ .Release.Namespace }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}-configmap

