name: eventrouter
replicaCount: 1
image: quay.io/samsung_cnct/eventrouter-container:0.1.1-4dc3172e88e2c81230aaf98c3033d1575444bb72
imagePullPolicy: IfNotPresent
config:
  sink: stdout
test:
  image: quay.io/samsung_cnct/e2etester:prod
